services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PGPORT: 5532
    ports:
      - "5532:5532"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    build:
      context: ./WebApi
    container_name: web-app
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  angular:
    build:
      context: ./Client
    container_name: angular-app
    ports:
      - "4200:4200"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
